#pragma once

// ============================================================================
// HtmlRenderer.hpp
// Auto-generated by DynHTML Web Builder
// ============================================================================

#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <cstdint>
#include <algorithm>
#if defined(_WIN32)
#include <d3d11.h>
#include <d3dcompiler.h>
#pragma comment(lib, "d3d11.lib")
#pragma comment(lib, "d3dcompiler.lib")
#endif

namespace dynhtml {

    typedef uint8_t u8;

    struct Color { u8 r, g, b, a; };
    struct Rect { float x, y, w, h; };
    struct SurfaceConfig {
        bool useHardwareAcceleration = true;
        int maxTextureSize = 4096;
    };

    // Simplified DOM Node
    struct Node {
        std::string tag;
        std::string text;
        Rect bounds{};
        Color bgColor = { 0,0,0,0 };
        Color textColor = { 0,0,0,0 };
        float borderRadius = 0.f;

        // Advanced WebKit-like Visual Effects
        bool hasBackdropBlur = false;
        float backdropBlurRadius = 0.f;
        bool hasLinearGradient = false;
        Color gradientStart = { 0,0,0,0 };
        Color gradientEnd = { 0,0,0,0 };

        // Core Layout
        std::vector<std::unique_ptr<Node>> children;
    };

    class HtmlRenderer {
    public:
        explicit HtmlRenderer(SurfaceConfig cfg = {}) : m_cfg(cfg) {}
        ~HtmlRenderer() { Cleanup(); }

        void SetHTML(std::string html) {
            m_html = html;
            ParseHTML();
        }

        void SetViewport(int width, int height, float dpiScale = 1.0f) {
            m_surfaceW = width;
            m_surfaceH = height;
            Layout();
        }

#if defined(_WIN32)
        void SetBackdropTexture(ID3D11ShaderResourceView* srv, int width, int height) {
            m_backdropSRV = srv;
            m_backdropW = width;
            m_backdropH = height;
        }

        void SetBackdropVideoRect(float x, float y, float w, float h) {
            m_backdropVideoRect = { x, y, w, h };
        }

        // The glass renderer receives the raw video SRV, not the already
        // composited ImGui frame. Feed the ambient procedural field into this
        // renderer explicitly so it is actually visible THROUGH the glass.
        void SetBackdropAmbientEffect(float timeSeconds, float opacity) {
            m_backdropAmbientTime = timeSeconds;
            m_backdropAmbientOpacity = std::clamp(opacity, 0.0f, 1.0f);
        }

        void InitializeDX11(ID3D11Device* device, ID3D11DeviceContext* context) {
            m_device = device;
            m_context = context;
            if (!device || !context) return;

            const char* hlsl = R"(
        struct PS_INPUT { float4 pos : SV_POSITION; float2 uv : TEXCOORD; };

        cbuffer BlurCB : register(b0) {
            float sourceWidth;
            float sourceHeight;
            float blurRadius;
            float isPass1;
            
            float4 clipRect; // x, y, w, h in UV space
            
            float isVertical;
            float backdropW;
            float backdropH;
            float pad2;

            float4 videoRect; // NEW: x,y,w,h in screen pixels

            float ambientTime;
            float ambientOpacity;
            float2 ambientPad;
        };

        PS_INPUT VSMain(uint id : SV_VertexID) {
            PS_INPUT output;
            float2 texcoords = float2((id << 1) & 2, id & 2);
            output.pos = float4(texcoords * float2(2, -2) + float2(-1, 1), 0, 1);
            output.uv = texcoords;
            return output;
        }

        Texture2D shaderTexture : register(t0);
        SamplerState SampleType : register(s0);

        float BackdropHash21(float2 p) {
            p = frac(p * float2(123.34, 456.21));
            p += dot(p, p + 45.32);
            return frac(p.x * p.y);
        }

        float BackdropNoise(float2 p) {
            float2 i = floor(p);
            float2 f = frac(p);
            f = f * f * (3.0 - 2.0 * f);

            float a = BackdropHash21(i);
            float b = BackdropHash21(i + float2(1.0, 0.0));
            float c = BackdropHash21(i + float2(0.0, 1.0));
            float d = BackdropHash21(i + float2(1.0, 1.0));
            return lerp(lerp(a, b, f.x), lerp(c, d, f.x), f.y);
        }

        float BackdropFbm(float2 p) {
            float v = 0.0;
            float a = 0.5;

            [unroll]
            for (int i = 0; i < 4; ++i) {
                v += BackdropNoise(p) * a;
                p = float2(
                    p.x * 1.62 - p.y * 1.18,
                    p.x * 1.18 + p.y * 1.62
                ) + 9.13;
                a *= 0.5;
            }
            return v;
        }

        float3 BackdropAmbientField(float2 localUV) {
            // Convert a renderer-local UV (e.g. the short header surface) back
            // into full-player UV space so the field lines up across all glass.
            float2 localPx = localUV * float2(sourceWidth, sourceHeight);
            float2 fullResolution = max(float2(backdropW, backdropH), float2(1.0, 1.0));
            float2 uv = localPx / fullResolution;

            float2 p = uv - 0.5;
            p.x *= fullResolution.x / fullResolution.y;

            float t = ambientTime * 0.16;
            float n1 = BackdropFbm(p * 2.15 + float2(t * 0.75, -t * 0.42));
            float n2 = BackdropFbm(p * 3.05 + float2(-t * 0.48, t * 0.68) + n1 * 1.35);
            float n3 = BackdropFbm(p * 4.30 + float2(t * 0.21, t * 0.31) + n2 * 0.95);

            float2 warp = float2(n1 - 0.5, n2 - 0.5);
            float2 q = p + warp * 0.30;

            float ribbonA = exp(-abs(q.y + sin(q.x * 2.2 + t * 2.7) * 0.11 + (n2 - 0.5) * 0.25) * 7.0);
            float ribbonB = exp(-abs(q.y - 0.18 + cos(q.x * 2.8 - t * 2.0) * 0.13 - (n1 - 0.5) * 0.22) * 8.5);
            float ribbonC = exp(-abs(q.y + 0.23 + sin(q.x * 3.6 + t * 1.3) * 0.08 + (n3 - 0.5) * 0.18) * 10.0);

            float3 field = 0.0;
            field += float3(0.24, 0.075, 0.62) * ribbonA * (0.34 + n3 * 0.40);
            field += float3(0.035, 0.24, 0.62) * ribbonB * (0.22 + n1 * 0.30);
            field += float3(0.33, 0.07, 0.45) * ribbonC * (0.16 + n2 * 0.22);

            float filament = pow(saturate(1.0 - abs(n2 - n1) * 3.2), 7.0);
            field += float3(0.12, 0.14, 0.34) * filament * 0.18;
            return field;
        }

        float4 BlurPS(PS_INPUT input) : SV_TARGET {
            float2 sampleUV = input.uv;
            
            // Map backdrop UVs strictly relative to header bounds or video bounds
            if (isPass1 > 0.5) {
                if (videoRect.z > 0.0) {
                    float2 screenPx = sampleUV * float2(sourceWidth, sourceHeight);
                    float2 vidUV = (screenPx - videoRect.xy) / videoRect.zw;
                    if (vidUV.x < 0.0 || vidUV.x > 1.0 || vidUV.y < 0.0 || vidUV.y > 1.0) {
                        return float4(0, 0, 0, 1.0);
                    }
                    sampleUV = vidUV;
                } else {
                    sampleUV.x *= (sourceWidth / backdropW);
                    sampleUV.y *= (sourceHeight / backdropH);
                }
            }

            int r = (int)blurRadius;

            // Final CPU overlay copy. This is the actual tinted/glass surface
            // drawn OVER the blurred backdrop, so the procedural ambient field
            // must be mixed here too or an 80%-opaque background hides it.
            if (r == 0) {
                float4 base = shaderTexture.SampleLevel(SampleType, sampleUV, 0);

                if (ambientOpacity > 0.0001 && base.a > 0.001) {
                    float3 surfaceAmbient = BackdropAmbientField(input.uv);
                    float surfaceMask = saturate(base.a * 1.15);
                    base.rgb = saturate(
                        base.rgb +
                        surfaceAmbient * ambientOpacity * surfaceMask);
                }

                return base;
            }

            // Out of bounds processing
            if (input.uv.x < clipRect.x || input.uv.x > clipRect.x + clipRect.z ||
                input.uv.y < clipRect.y || input.uv.y > clipRect.y + clipRect.w) {
                float4 fallback = shaderTexture.SampleLevel(SampleType, sampleUV, 0);
                fallback.a = 1.0;
                return fallback;
            }

            float2 texelSize = float2(1.0f / sourceWidth, 1.0f / sourceHeight);
            float4 color = float4(0,0,0,0);
            float total = 0.0;
            
            for(int i = -r; i <= r; i++) {
                float2 offset = isVertical > 0.5 ? float2(0, (float)i) : float2((float)i, 0);
                float2 iterUV = input.uv + offset * texelSize;
                
                iterUV.x = clamp(iterUV.x, clipRect.x, clipRect.x + clipRect.z);
                iterUV.y = clamp(iterUV.y, clipRect.y, clipRect.y + clipRect.w);
                
                if (isPass1 > 0.5) {
                    if (videoRect.z > 0.0) {
                        float2 screenPx = iterUV * float2(sourceWidth, sourceHeight);
                        float2 vidUV = (screenPx - videoRect.xy) / videoRect.zw;
                        if (vidUV.x < 0.0 || vidUV.x > 1.0 || vidUV.y < 0.0 || vidUV.y > 1.0) {
                            color += float4(0, 0, 0, 1.0);
                            total += 1.0;
                            continue;
                        }
                        iterUV = vidUV;
                    } else {
                        iterUV.x *= (sourceWidth / backdropW);
                        iterUV.y *= (sourceHeight / backdropH);
                    }
                }
                
                color += shaderTexture.SampleLevel(SampleType, iterUV, 0);
                total += 1.0;
            }
            
            float4 finalColor = color / total;

            // Apply the ambient procedural field only after the second blur pass
            // so it is injected once into the finished glass backdrop.
            if (isVertical > 0.5 && ambientOpacity > 0.0001) {
                float3 ambient = BackdropAmbientField(input.uv);
                finalColor.rgb = saturate(finalColor.rgb + ambient * ambientOpacity);
            }

            finalColor.a = 1.0; // Force hardware blur pass to be perfectly opaque!
            return finalColor;
        }
        )";

            ID3D10Blob* shaderBlob = nullptr;
            D3DCompile(hlsl, strlen(hlsl), "VS", NULL, NULL, "VSMain", "vs_5_0", 0, 0, &shaderBlob, NULL);
            if (shaderBlob) {
                device->CreateVertexShader(shaderBlob->GetBufferPointer(), shaderBlob->GetBufferSize(), NULL, &m_vs);
                shaderBlob->Release();
            }

            D3DCompile(hlsl, strlen(hlsl), "PS", NULL, NULL, "BlurPS", "ps_5_0", 0, 0, &shaderBlob, NULL);
            if (shaderBlob) {
                device->CreatePixelShader(shaderBlob->GetBufferPointer(), shaderBlob->GetBufferSize(), NULL, &m_blurPS);
                shaderBlob->Release();
            }

            D3D11_BUFFER_DESC bd = {};
            bd.Usage = D3D11_USAGE_DYNAMIC;
            bd.ByteWidth = sizeof(float) * 20; // 5 float4s (last block = ambient time/opacity/pad)
            bd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
            bd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
            device->CreateBuffer(&bd, NULL, &m_blurCB);

            D3D11_SAMPLER_DESC sampDesc = {};
            sampDesc.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
            sampDesc.AddressU = D3D11_TEXTURE_ADDRESS_CLAMP;
            sampDesc.AddressV = D3D11_TEXTURE_ADDRESS_CLAMP;
            sampDesc.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
            sampDesc.ComparisonFunc = D3D11_COMPARISON_NEVER;
            device->CreateSamplerState(&sampDesc, &m_sampler);

            // Correct Straight-Alpha Blend State
            D3D11_BLEND_DESC blendDesc = {};
            blendDesc.RenderTarget[0].BlendEnable = TRUE;
            blendDesc.RenderTarget[0].SrcBlend = D3D11_BLEND_SRC_ALPHA;
            blendDesc.RenderTarget[0].DestBlend = D3D11_BLEND_INV_SRC_ALPHA;
            blendDesc.RenderTarget[0].BlendOp = D3D11_BLEND_OP_ADD;
            blendDesc.RenderTarget[0].SrcBlendAlpha = D3D11_BLEND_ONE;
            blendDesc.RenderTarget[0].DestBlendAlpha = D3D11_BLEND_INV_SRC_ALPHA;
            blendDesc.RenderTarget[0].BlendOpAlpha = D3D11_BLEND_OP_ADD;
            blendDesc.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
            device->CreateBlendState(&blendDesc, &m_blendState);
        }
#endif

        void Tick(float dtSeconds) {
            // Animation tick
        }

        bool Render() {
            if (m_surfaceW <= 0 || m_surfaceH <= 0) return false;

            m_cpuPixels.resize(m_surfaceW * m_surfaceH * 4, 0);
            std::fill(m_cpuPixels.begin(), m_cpuPixels.end(), 0);

            if (m_dom) {
                RasterizeNode(*m_dom);
            }
            CompositeDX11();
            return true;
        }

        void* TextureHandle() const {
#if defined(_WIN32)
            return (void*)m_outputSRV;
#else
            return nullptr;
#endif
        }

    private:
        void ParseHTML() {
            m_dom = std::make_unique<Node>();
            m_dom->tag = "div";
            m_dom->bounds = { 0, 0, (float)m_surfaceW, (float)m_surfaceH };
            m_dom->hasBackdropBlur = true;
            m_dom->backdropBlurRadius = 12.0f;
            m_dom->bgColor = { 17, 24, 39, 204 }; // background: rgba(17, 24, 39, 0.8)

            // Build the border-bottom child organically into the DOM!
            auto borderBottom = std::make_unique<Node>();
            borderBottom->tag = "div";
            borderBottom->bgColor = { 255, 255, 255, 20 }; // rgba(255, 255, 255, 0.08)
            m_dom->children.push_back(std::move(borderBottom));
        }

        void Layout() {
            if (m_dom) {
                m_dom->bounds = { 0, 0, (float)m_surfaceW, (float)m_surfaceH };
                if (!m_dom->children.empty()) {
                    // Lock border-bottom to the bottom pixel
                    m_dom->children[0]->bounds = { 0, (float)m_surfaceH - 1.0f, (float)m_surfaceW, 1.0f };
                }
            }
        }

        void RasterizeNode(const Node& node) {
            FillRect(node.bounds, node.bgColor);

            for (const auto& child : node.children) {
                RasterizeNode(*child);
            }
        }

        void FillRect(const Rect& r, Color c) {
            if (c.a == 0) return;

            int startX = (std::max)(0, static_cast<int>(r.x));
            int startY = (std::max)(0, static_cast<int>(r.y));
            int endX = (std::min)(m_surfaceW, static_cast<int>(r.x + r.w));
            int endY = (std::min)(m_surfaceH, static_cast<int>(r.y + r.h));

            float srcA = c.a / 255.0f;

            for (int y = startY; y < endY; ++y) {
                for (int x = startX; x < endX; ++x) {
                    int idx = (y * m_surfaceW + x) * 4;
                    if (idx + 3 < m_cpuPixels.size()) {
                        float dstA = m_cpuPixels[idx + 3] / 255.0f;

                        // Perfectly un-premultiplied straight alpha compositor (Fixes invisiblity bug)
                        float outA = srcA + dstA * (1.0f - srcA);

                        if (outA > 0.0f) {
                            float rOut = (c.r * srcA + m_cpuPixels[idx] * dstA * (1.0f - srcA)) / outA;
                            float gOut = (c.g * srcA + m_cpuPixels[idx + 1] * dstA * (1.0f - srcA)) / outA;
                            float bOut = (c.b * srcA + m_cpuPixels[idx + 2] * dstA * (1.0f - srcA)) / outA;

                            m_cpuPixels[idx] = static_cast<u8>((std::min)(255.0f, rOut));
                            m_cpuPixels[idx + 1] = static_cast<u8>((std::min)(255.0f, gOut));
                            m_cpuPixels[idx + 2] = static_cast<u8>((std::min)(255.0f, bOut));
                            m_cpuPixels[idx + 3] = static_cast<u8>((std::min)(255.0f, outA * 255.0f));
                        }
                    }
                }
            }
        }

        void CleanupTextures() {
#if defined(_WIN32)
            if (m_outputTexture) { m_outputTexture->Release(); m_outputTexture = nullptr; }
            if (m_outputSRV) { m_outputSRV->Release(); m_outputSRV = nullptr; }
            if (m_outputRTV) { m_outputRTV->Release(); m_outputRTV = nullptr; }
            if (m_blurTempTexture) { m_blurTempTexture->Release(); m_blurTempTexture = nullptr; }
            if (m_blurTempSRV) { m_blurTempSRV->Release(); m_blurTempSRV = nullptr; }
            if (m_blurTempRTV) { m_blurTempRTV->Release(); m_blurTempRTV = nullptr; }
            if (m_cpuTexture) { m_cpuTexture->Release(); m_cpuTexture = nullptr; }
            if (m_cpuSRV) { m_cpuSRV->Release(); m_cpuSRV = nullptr; }
#endif
        }

        void Cleanup() {
#if defined(_WIN32)
            CleanupTextures();
            if (m_vs) { m_vs->Release(); m_vs = nullptr; }
            if (m_blurPS) { m_blurPS->Release(); m_blurPS = nullptr; }
            if (m_sampler) { m_sampler->Release(); m_sampler = nullptr; }
            if (m_blurCB) { m_blurCB->Release(); m_blurCB = nullptr; }
            if (m_blendState) { m_blendState->Release(); m_blendState = nullptr; }
#endif
        }

        void EnsureTextures() {
#if defined(_WIN32)
            if (!m_device || m_surfaceW == 0) return;

            if (m_outputTexture) {
                D3D11_TEXTURE2D_DESC desc;
                m_outputTexture->GetDesc(&desc);
                if (desc.Width == static_cast<UINT>(m_surfaceW) && desc.Height == static_cast<UINT>(m_surfaceH)) return;
                CleanupTextures(); // Re-create on resize
            }

            D3D11_TEXTURE2D_DESC td = {};
            td.Width = m_surfaceW;
            td.Height = m_surfaceH;
            td.MipLevels = 1;
            td.ArraySize = 1;
            td.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
            td.SampleDesc.Count = 1;
            td.Usage = D3D11_USAGE_DEFAULT;
            td.BindFlags = D3D11_BIND_SHADER_RESOURCE | D3D11_BIND_RENDER_TARGET;

            m_device->CreateTexture2D(&td, NULL, &m_outputTexture);
            if (m_outputTexture) {
                m_device->CreateShaderResourceView(m_outputTexture, NULL, &m_outputSRV);
                m_device->CreateRenderTargetView(m_outputTexture, NULL, &m_outputRTV);
            }

            m_device->CreateTexture2D(&td, NULL, &m_blurTempTexture);
            if (m_blurTempTexture) {
                m_device->CreateShaderResourceView(m_blurTempTexture, NULL, &m_blurTempSRV);
                m_device->CreateRenderTargetView(m_blurTempTexture, NULL, &m_blurTempRTV);
            }

            td.Usage = D3D11_USAGE_DYNAMIC;
            td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
            td.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
            m_device->CreateTexture2D(&td, NULL, &m_cpuTexture);
            if (m_cpuTexture) {
                m_device->CreateShaderResourceView(m_cpuTexture, NULL, &m_cpuSRV);
            }
#endif
        }

        void RenderTranslucentNodes(const Node& node) {
#if defined(_WIN32)
            if (node.hasBackdropBlur && m_backdropSRV && m_blurTempRTV && m_outputRTV) {
                D3D11_MAPPED_SUBRESOURCE mapped;
                m_context->Map(m_blurCB, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped);
                float* cbData = (float*)mapped.pData;
                cbData[0] = (float)m_surfaceW;
                cbData[1] = (float)m_surfaceH;
                cbData[2] = node.backdropBlurRadius;
                cbData[3] = 1.0f;
                cbData[4] = node.bounds.x / m_surfaceW;
                cbData[5] = node.bounds.y / m_surfaceH;
                cbData[6] = node.bounds.w / m_surfaceW;
                cbData[7] = node.bounds.h / m_surfaceH;
                cbData[8] = 0.0f; // isVertical
                cbData[9] = (float)(m_backdropW > 0 ? m_backdropW : m_surfaceW);
                cbData[10] = (float)(m_backdropH > 0 ? m_backdropH : m_surfaceH);
                cbData[11] = 0.0f;
                cbData[12] = m_backdropVideoRect.x;
                cbData[13] = m_backdropVideoRect.y;
                cbData[14] = m_backdropVideoRect.w;
                cbData[15] = m_backdropVideoRect.h;
                cbData[16] = m_backdropAmbientTime;
                cbData[17] = m_backdropAmbientOpacity;
                cbData[18] = 0.0f;
                cbData[19] = 0.0f;
                m_context->Unmap(m_blurCB, 0);

                // Pass 1: Horizontal Blur (Backdrop -> Temp)
                m_context->OMSetRenderTargets(1, &m_blurTempRTV, NULL);
                m_context->PSSetShaderResources(0, 1, &m_backdropSRV);
                m_context->Draw(3, 0);

                // Pass 2: Vertical Blur (Temp -> Output)
                m_context->Map(m_blurCB, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped);
                cbData = (float*)mapped.pData;
                cbData[0] = (float)m_surfaceW;
                cbData[1] = (float)m_surfaceH;
                cbData[2] = node.backdropBlurRadius;
                cbData[3] = 0.0f;
                cbData[4] = node.bounds.x / m_surfaceW;
                cbData[5] = node.bounds.y / m_surfaceH;
                cbData[6] = node.bounds.w / m_surfaceW;
                cbData[7] = node.bounds.h / m_surfaceH;
                cbData[8] = 1.0f; // isVertical
                cbData[9] = (float)(m_backdropW > 0 ? m_backdropW : m_surfaceW);
                cbData[10] = (float)(m_backdropH > 0 ? m_backdropH : m_surfaceH);
                cbData[11] = 0.0f;
                cbData[12] = m_backdropVideoRect.x;
                cbData[13] = m_backdropVideoRect.y;
                cbData[14] = m_backdropVideoRect.w;
                cbData[15] = m_backdropVideoRect.h;
                cbData[16] = m_backdropAmbientTime;
                cbData[17] = m_backdropAmbientOpacity;
                cbData[18] = 0.0f;
                cbData[19] = 0.0f;
                m_context->Unmap(m_blurCB, 0);

                m_context->OMSetRenderTargets(1, &m_outputRTV, NULL);
                m_context->PSSetShaderResources(0, 1, &m_blurTempSRV);
                m_context->Draw(3, 0);
            }

            for (const auto& child : node.children) {
                RenderTranslucentNodes(*child);
            }
#endif
        }

        void CompositeDX11() {
#if defined(_WIN32)
            if (!m_device || !m_context || m_cpuPixels.empty()) return;
            EnsureTextures();
            if (!m_outputTexture) return;

            D3D11_MAPPED_SUBRESOURCE mapped;
            if (SUCCEEDED(m_context->Map(m_cpuTexture, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) {
                for (int i = 0; i < m_surfaceH; ++i) {
                    memcpy((u8*)mapped.pData + i * mapped.RowPitch, &m_cpuPixels[i * m_surfaceW * 4], m_surfaceW * 4);
                }
                m_context->Unmap(m_cpuTexture, 0);
            }

            // 1. SAVE STATE
            ID3D11RenderTargetView* oldRTV = nullptr;
            ID3D11DepthStencilView* oldDSV = nullptr;
            m_context->OMGetRenderTargets(1, &oldRTV, &oldDSV);
            D3D11_VIEWPORT oldVP;
            UINT numVP = 1;
            m_context->RSGetViewports(&numVP, &oldVP);
            ID3D11ShaderResourceView* oldSRV = nullptr;
            m_context->PSGetShaderResources(0, 1, &oldSRV);
            ID3D11BlendState* oldBlend = nullptr;
            float oldBlendFactor[4];
            UINT oldSampleMask;
            m_context->OMGetBlendState(&oldBlend, oldBlendFactor, &oldSampleMask);
            ID3D11Buffer* oldCB = nullptr;
            m_context->PSGetConstantBuffers(0, 1, &oldCB);
            ID3D11PixelShader* oldPS = nullptr;
            m_context->PSGetShader(&oldPS, nullptr, 0);
            ID3D11VertexShader* oldVS = nullptr;
            m_context->VSGetShader(&oldVS, nullptr, 0);
            D3D11_PRIMITIVE_TOPOLOGY oldTopology;
            m_context->IAGetPrimitiveTopology(&oldTopology);
            ID3D11InputLayout* oldLayout = nullptr;
            m_context->IAGetInputLayout(&oldLayout);

            // Bind common pipeline
            m_context->IASetInputLayout(nullptr);
            m_context->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
            m_context->VSSetShader(m_vs, NULL, 0);
            m_context->PSSetShader(m_blurPS, NULL, 0);
            m_context->PSSetSamplers(0, 1, &m_sampler);
            m_context->PSSetConstantBuffers(0, 1, &m_blurCB);

            D3D11_VIEWPORT vp = { 0.0f, 0.0f, (float)m_surfaceW, (float)m_surfaceH, 0.0f, 1.0f };
            m_context->RSSetViewports(1, &vp);

            float clearColor[4] = { 0, 0, 0, 0 };
            m_context->ClearRenderTargetView(m_outputRTV, clearColor);

            // Force opaque blend state before drawing translucent blur passes! (Fixes invisible VLC bug)
            m_context->OMSetBlendState(nullptr, nullptr, 0xffffffff);

            if (m_dom) {
                RenderTranslucentNodes(*m_dom);
            }

            // Final Composite: Draw CPUPixels over Output with precise un-premultiplied Alpha Blending
            m_context->OMSetRenderTargets(1, &m_outputRTV, NULL);
            float blendFactor[4] = { 1,1,1,1 };
            m_context->OMSetBlendState(m_blendState, blendFactor, 0xffffffff);

            m_context->Map(m_blurCB, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped);
            float* cbData = (float*)mapped.pData;
            cbData[0] = (float)m_surfaceW;
            cbData[1] = (float)m_surfaceH;
            cbData[2] = 0.0f; // zero blur to activate precise CPU alpha copy mode
            cbData[3] = 0.0f; // isPass1 -> False
            cbData[4] = 0.0f; cbData[5] = 0.0f; cbData[6] = 1.0f; cbData[7] = 1.0f;
            cbData[8] = 0.0f;
            cbData[9] = (float)m_surfaceW; cbData[10] = (float)m_surfaceH; cbData[11] = 0.0f;
            cbData[12] = 0.0f; cbData[13] = 0.0f; cbData[14] = 0.0f; cbData[15] = 0.0f;
            cbData[16] = m_backdropAmbientTime;
            cbData[17] = m_backdropAmbientOpacity; // Keep the ambient field visible inside the final glass tint.
            cbData[18] = 0.0f; cbData[19] = 0.0f;
            m_context->Unmap(m_blurCB, 0);

            m_context->PSSetShaderResources(0, 1, &m_cpuSRV);
            m_context->Draw(3, 0);

            // Clean up bindings before restore
            ID3D11ShaderResourceView* nullSRV[1] = { nullptr };
            m_context->PSSetShaderResources(0, 1, nullSRV);

            // 2. RESTORE STATE
            m_context->OMSetRenderTargets(1, &oldRTV, oldDSV);
            if (oldRTV) oldRTV->Release();
            if (oldDSV) oldDSV->Release();
            m_context->RSSetViewports(numVP, &oldVP);
            m_context->PSSetShaderResources(0, 1, &oldSRV);
            if (oldSRV) oldSRV->Release();
            m_context->OMSetBlendState(oldBlend, oldBlendFactor, oldSampleMask);
            if (oldBlend) oldBlend->Release();
            m_context->PSSetConstantBuffers(0, 1, &oldCB);
            if (oldCB) oldCB->Release();
            m_context->PSSetShader(oldPS, nullptr, 0);
            if (oldPS) oldPS->Release();
            m_context->VSSetShader(oldVS, nullptr, 0);
            if (oldVS) oldVS->Release();
            m_context->IASetPrimitiveTopology(oldTopology);
            m_context->IASetInputLayout(oldLayout);
            if (oldLayout) oldLayout->Release();
#endif
        }

        ID3D11Device* m_device{ nullptr };
        ID3D11DeviceContext* m_context{ nullptr };
        ID3D11Texture2D* m_outputTexture{ nullptr };
        ID3D11ShaderResourceView* m_outputSRV{ nullptr };
        ID3D11RenderTargetView* m_outputRTV{ nullptr };
        ID3D11Texture2D* m_blurTempTexture{ nullptr };
        ID3D11ShaderResourceView* m_blurTempSRV{ nullptr };
        ID3D11RenderTargetView* m_blurTempRTV{ nullptr };
        ID3D11Texture2D* m_cpuTexture{ nullptr };
        ID3D11ShaderResourceView* m_cpuSRV{ nullptr };
        ID3D11VertexShader* m_vs{ nullptr };
        ID3D11PixelShader* m_blurPS{ nullptr };
        ID3D11SamplerState* m_sampler{ nullptr };
        ID3D11Buffer* m_blurCB{ nullptr };
        ID3D11BlendState* m_blendState{ nullptr };

        SurfaceConfig m_cfg;
        std::string m_html;
        int m_surfaceW{ 0 };
        int m_surfaceH{ 0 };
        std::unique_ptr<Node> m_dom;
        std::vector<u8> m_cpuPixels;

#if defined(_WIN32)
        ID3D11ShaderResourceView* m_backdropSRV{ nullptr };
#else
        void* m_backdropTexture{ nullptr };
#endif
        int m_backdropW{ 0 };
        int m_backdropH{ 0 };
        Rect m_backdropVideoRect{ 0,0,0,0 };
        float m_backdropAmbientTime{ 0.0f };
        float m_backdropAmbientOpacity{ 0.0f };
    };

} // namespace dynhtml